allowBuilds:
  "@clerk/shared": false
  "@prisma/client": true
  "@prisma/engines": true
  "@sentry/cli": true
  "@tailwindcss/oxide": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

overrides:
  "@types/react": 19.2.15
  "@types/react-dom": 19.2.3
