import { type PrismaClient, CustomFieldType, type Prisma } from '@orm'

type TemplateFieldData = {
  name: string
  label: string
  type: CustomFieldType
  options?: { value: string; label: string }[]
  defaultValue?: string | number | boolean | null
  placeholder?: string
  isRequired: boolean
  displayOrder: number
  rangeMin?: number
  rangeMax?: number
  rangeUnit?: string
  rangeDecimals?: number
}

type CustomFieldTemplateData = {
  name: string
  fields: TemplateFieldData[]
}

const customFieldTemplates: CustomFieldTemplateData[] = [
  {
    name: 'Ryujinx Fields',
    fields: [
      {
        name: 'graphics_api',
        label: 'Graphics API',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan (Recommended)', label: 'Vulkan (Recommended)' },
          { value: 'OpenGL', label: 'OpenGL' },
        ],
        defaultValue: 'Vulkan (Recommended)',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.SELECT,
        options: [
          {
            value: 'Match Emulated Display (Default)',
            label: 'Match Emulated Display (Default)',
          },
          { value: 'Off', label: 'Off' },
          { value: 'Double Buffering', label: 'Double Buffering' },
        ],
        defaultValue: 'Match Emulated Display (Default)',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'async_shader_compilation',
        label: 'Async Shader Compilation',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'memory_manager',
        label: 'Memory Manager Mode',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Host Managed (Default)', label: 'Host Managed (Default)' },
          { value: 'Software', label: 'Software' },
        ],
        defaultValue: 'Host Managed (Default)',
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'system_region',
        label: 'System Region',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'USA', label: 'USA' },
          { value: 'Europe', label: 'Europe' },
          { value: 'Japan', label: 'Japan' },
          { value: 'Australia', label: 'Australia' },
          { value: 'China', label: 'China' },
          { value: 'Korea', label: 'Korea' },
          { value: 'Taiwan', label: 'Taiwan' },
        ],
        defaultValue: 'USA',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'audio_backend',
        label: 'Audio Backend (PC)',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'SDL2', label: 'SDL2' },
          { value: 'OpenAL', label: 'OpenAL' },
          { value: 'SoundIO', label: 'SoundIO' },
          { value: 'XAudio2 (Windows)', label: 'XAudio2 (Windows)' },
        ],
        defaultValue: 'SDL2',
        placeholder: 'Windows/Linux/Mac audio backend (PC)',
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'texture_recompression',
        label: 'Texture Recompression',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'ptc_cache',
        label: 'PPTC (Profiled Persistent Translation Cache)',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 9,
      },
    ],
  },
  {
    name: 'Cemu Fields',
    fields: [
      {
        name: 'graphics_api',
        label: 'Graphics API',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan (Recommended)', label: 'Vulkan (Recommended)' },
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'Direct3D 12', label: 'Direct3D 12' },
        ],
        defaultValue: 'Vulkan (Recommended)',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.SELECT,
        options: [
          {
            value: 'Match Emulated Display (Experimental)',
            label: 'Match Emulated Display (Experimental)',
          },
          { value: 'Off', label: 'Off' },
          { value: 'Double Buffering', label: 'Double Buffering' },
        ],
        defaultValue: 'Match Emulated Display (Experimental)',
        isRequired: false,
        displayOrder: 2,
      },
      {
        name: 'async_shader_compiler',
        label: 'Async Shader Compiler',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'gpu_buffer_cache_accuracy',
        label: 'GPU Buffer Cache Accuracy',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'High (Slow)', label: 'High (Slow)' },
          { value: 'Medium (Default)', label: 'Medium (Default)' },
          { value: 'Low (Fast)', label: 'Low (Fast)' },
        ],
        defaultValue: 'Medium (Default)',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'console_region',
        label: 'Console Region',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto (Default)', label: 'Auto (Default)' },
          { value: 'USA', label: 'USA' },
          { value: 'Europe', label: 'Europe' },
          { value: 'Japan', label: 'Japan' },
          { value: 'China', label: 'China' },
          { value: 'Korea', label: 'Korea' },
          { value: 'Taiwan', label: 'Taiwan' },
        ],
        defaultValue: 'Auto (Default)',
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'upscale_filter',
        label: 'Upscale Filter',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Bilinear', label: 'Bilinear' },
          { value: 'Bicubic', label: 'Bicubic' },
        ],
        defaultValue: 'Bilinear',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'audio_api',
        label: 'Audio API (PC)',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'XAudio2 (Windows)', label: 'XAudio2 (Windows)' },
          { value: 'Cubeb (Mac/Linux)', label: 'Cubeb (Mac/Linux)' },
        ],
        defaultValue: 'XAudio2 (Windows)',
        placeholder: 'Audio backend for Windows/Mac/Linux (PC)',
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'triple_buffering',
        label: 'Triple Buffering',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'precompiled_shaders',
        label: 'Precompiled Shaders',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 9,
      },
    ],
  },
  {
    name: 'AetherSX2 Fields',
    fields: [
      {
        name: 'renderer',
        label: 'Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan (Recommended)', label: 'Vulkan (Recommended)' },
          { value: 'OpenGL ES', label: 'OpenGL ES' },
        ],
        defaultValue: 'Vulkan (Recommended)',
        placeholder: 'Graphics renderer for Android devices (Android)',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'bios_region',
        label: 'BIOS Region',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'USA (NTSC-U)', label: 'USA (NTSC-U)' },
          { value: 'Europe (PAL)', label: 'Europe (PAL)' },
          { value: 'Japan (NTSC-J)', label: 'Japan (NTSC-J)' },
        ],
        defaultValue: 'USA (NTSC-U)',
        isRequired: true,
        displayOrder: 2,
      },
      {
        name: 'resolution_scale',
        label: 'Internal Resolution',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 3,
        rangeMin: 1,
        rangeMax: 4,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'multi_threaded_vu',
        label: 'Multi-threaded VU',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'speed_hacks',
        label: 'Enable Speed Hacks',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'threading_mode',
        label: 'Threading Mode',
        type: CustomFieldType.SELECT,
        options: [
          {
            value: 'Multi-threaded (Default)',
            label: 'Multi-threaded (Default)',
          },
          { value: 'Single-threaded', label: 'Single-threaded' },
        ],
        defaultValue: 'Multi-threaded (Default)',
        placeholder: 'CPU threading configuration for Android (Android)',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'texture_filtering',
        label: 'Texture Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Bilinear (PS2)', label: 'Bilinear (PS2)' },
          { value: 'Force Bilinear', label: 'Force Bilinear' },
          { value: 'Off', label: 'Off' },
        ],
        defaultValue: 'Bilinear (PS2)',
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'frame_pacing',
        label: 'Frame Pacing',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'fast_cdvd',
        label: 'Fast CDVD',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 9,
      },
    ],
  },
  {
    name: 'Dolphin Fields',
    fields: [
      {
        name: 'graphics_backend',
        label: 'Graphics Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan', label: 'Vulkan' },
          { value: 'Direct3D 11 (PC)', label: 'Direct3D 11 (PC)' },
          { value: 'Direct3D 12 (PC)', label: 'Direct3D 12 (PC)' },
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'OpenGL ES (Android)', label: 'OpenGL ES (Android)' },
          { value: 'Metal (macOS)', label: 'Metal (macOS)' },
        ],
        defaultValue: 'Vulkan',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'enable_dual_core',
        label: 'Enable Dual Core',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 2,
      },
      {
        name: 'dsp_emulator',
        label: 'DSP Emulator Engine',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'HLE (Fast, Default)', label: 'HLE (Fast, Default)' },
          { value: 'LLE (Accurate, Slow)', label: 'LLE (Accurate, Slow)' },
        ],
        defaultValue: 'HLE (Fast, Default)',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'internal_resolution',
        label: 'Internal Resolution',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 4,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'shader_compilation',
        label: 'Shader Compilation',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Specialized (Default)', label: 'Specialized (Default)' },
          { value: 'Hybrid Ubershaders', label: 'Hybrid Ubershaders' },
          { value: 'Exclusive Ubershaders', label: 'Exclusive Ubershaders' },
          { value: 'Skip Drawing', label: 'Skip Drawing' },
        ],
        defaultValue: 'Specialized (Default)',
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'anti_aliasing',
        label: 'Anti-Aliasing',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Off', label: 'Off' },
          { value: '2x MSAA', label: '2x MSAA' },
          { value: '4x MSAA', label: '4x MSAA' },
          { value: '8x MSAA', label: '8x MSAA' },
          { value: '2x SSAA', label: '2x SSAA' },
          { value: '4x SSAA', label: '4x SSAA' },
        ],
        defaultValue: 'Off',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'anisotropic_filtering',
        label: 'Anisotropic Filtering',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 7,
        rangeMin: 1,
        rangeMax: 16,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'skip_efb_access',
        label: 'Skip EFB Access from CPU',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 9,
      },
      {
        name: 'ignore_format_changes',
        label: 'Ignore Format Changes',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 10,
      },
    ],
  },
  {
    name: 'PCSX2 Fields',
    fields: [
      {
        name: 'renderer',
        label: 'Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan (Fastest)', label: 'Vulkan (Fastest)' },
          { value: 'OpenGL (Balance)', label: 'OpenGL (Balance)' },
          { value: 'Direct3D 11 (Fallback)', label: 'Direct3D 11 (Fallback)' },
          { value: 'Direct3D 12 (Fallback)', label: 'Direct3D 12 (Fallback)' },
          {
            value: 'Software (Most Accurate)',
            label: 'Software (Most Accurate)',
          },
        ],
        defaultValue: 'Vulkan (Fastest)',
        placeholder: 'Graphics renderer for Windows/Linux (PC)',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'internal_resolution',
        label: 'Internal Resolution',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto (4:3) Recommended', label: 'Auto (4:3) Recommended' },
          {
            value: 'Fit to Window/Fullscreen',
            label: 'Fit to Window/Fullscreen',
          },
          { value: 'Widescreen (16:9)', label: 'Widescreen (16:9)' },
        ],
        defaultValue: 'Auto (4:3) Recommended',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'texture_filtering',
        label: 'Texture Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Bilinear (PS2) Default', label: 'Bilinear (PS2) Default' },
          { value: 'Force Bilinear', label: 'Force Bilinear' },
          { value: 'Off', label: 'Off' },
        ],
        defaultValue: 'Bilinear (PS2) Default',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'anisotropic_filtering',
        label: 'Anisotropic Filtering',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 5,
        rangeMin: 1,
        rangeMax: 16,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'anti_aliasing',
        label: 'Anti-Aliasing (FXAA)',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'anti_blur',
        label: 'Anti Blur',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'deinterlacing',
        label: 'Deinterlacing',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Automatic (Default)', label: 'Automatic (Default)' },
          {
            value: 'Native Progressive Scan',
            label: 'Native Progressive Scan',
          },
          { value: 'Weave', label: 'Weave' },
          { value: 'Bob', label: 'Bob' },
          { value: 'Blend', label: 'Blend' },
        ],
        defaultValue: 'Automatic (Default)',
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'ee_cyclerate',
        label: 'EE Cycle Rate',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 9,
        rangeMin: -3,
        rangeMax: 3,
        rangeUnit: '',
        rangeDecimals: 0,
      },
      {
        name: 'vu_cycle_stealing',
        label: 'VU Cycle Stealing',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 10,
        rangeMin: 0,
        rangeMax: 4,
        rangeUnit: '',
        rangeDecimals: 0,
      },
    ],
  },
  {
    name: 'PPSSPP Fields',
    fields: [
      {
        name: 'backend',
        label: 'Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan (Recommended)', label: 'Vulkan (Recommended)' },
          { value: 'OpenGL (Android/PC)', label: 'OpenGL (Android/PC)' },
          { value: 'Direct3D 11 (PC)', label: 'Direct3D 11 (PC)' },
          { value: 'Direct3D 9 (PC)', label: 'Direct3D 9 (PC)' },
        ],
        defaultValue: 'Vulkan (Recommended)',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'rendering_resolution',
        label: 'Rendering Resolution',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'msaa',
        label: 'Antialiasing (MSAA)',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Off', label: 'Off' },
          { value: '2x MSAA', label: '2x MSAA' },
          { value: '4x MSAA', label: '4x MSAA' },
          { value: '8x MSAA', label: '8x MSAA' },
        ],
        defaultValue: 'Off',
        placeholder: 'Vulkan backend only (PC)',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'frame_skipping',
        label: 'Frame Skipping',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 5,
        rangeMin: 0,
        rangeMax: 5,
        rangeUnit: '',
        rangeDecimals: 0,
      },
      {
        name: 'texture_filtering',
        label: 'Texture Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto (Default)', label: 'Auto (Default)' },
          { value: 'Nearest', label: 'Nearest' },
          { value: 'Linear', label: 'Linear' },
          { value: 'Auto Max Quality', label: 'Auto Max Quality' },
        ],
        defaultValue: 'Auto (Default)',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'anisotropic_filtering',
        label: 'Anisotropic Filtering',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 7,
        rangeMin: 1,
        rangeMax: 16,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'texture_scaling',
        label: 'Texture Scaling',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Off', label: 'Off' },
          { value: 'xBRZ (Sharp)', label: 'xBRZ (Sharp)' },
          { value: 'Bicubic (Smooth)', label: 'Bicubic (Smooth)' },
          { value: 'Hybrid', label: 'Hybrid' },
        ],
        defaultValue: 'Off',
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'lower_resolution_effects',
        label: 'Lower Resolution for Effects',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Off', label: 'Off' },
          { value: 'Safe', label: 'Safe' },
          { value: 'Balanced', label: 'Balanced' },
          { value: 'Aggressive', label: 'Aggressive' },
        ],
        defaultValue: 'Off',
        isRequired: false,
        displayOrder: 9,
      },
      {
        name: 'multithreaded',
        label: 'Multithreaded (MT)',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 10,
      },
      {
        name: 'fast_memory',
        label: 'Fast Memory',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 11,
      },
    ],
  },
  {
    name: 'RetroArch Fields',
    fields: [
      {
        name: 'video_driver',
        label: 'Video Driver',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan', label: 'Vulkan' },
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'Direct3D 11', label: 'Direct3D 11' },
          { value: 'Direct3D 12', label: 'Direct3D 12' },
        ],
        defaultValue: 'Vulkan',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'video_scale',
        label: 'Video Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'frame_delay',
        label: 'Frame Delay',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 4,
        rangeMin: 0,
        rangeMax: 15,
        rangeUnit: 'ms',
        rangeDecimals: 0,
      },
      {
        name: 'hard_gpu_sync',
        label: 'Hard GPU Sync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'gpu_sync_frames',
        label: 'GPU Sync Frames',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 6,
        rangeMin: 0,
        rangeMax: 3,
        rangeUnit: '',
        rangeDecimals: 0,
      },
      {
        name: 'rewind',
        label: 'Rewind',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'run_ahead',
        label: 'Run-Ahead',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 8,
        rangeMin: 0,
        rangeMax: 6,
        rangeUnit: 'frames',
        rangeDecimals: 0,
      },
    ],
  },
  {
    name: 'Xenia Fields',
    fields: [
      {
        name: 'gpu',
        label: 'GPU Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan', label: 'Vulkan' },
          { value: 'Direct3D 12', label: 'Direct3D 12' },
        ],
        defaultValue: 'Vulkan',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 3,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'gamma_render_target_as_srgb',
        label: 'Gamma Render Target as sRGB',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'gpu_allow_invalid_fetch_constants',
        label: 'Allow Invalid Fetch Constants',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'cpu',
        label: 'CPU Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'x64', label: 'x64' },
          { value: 'Any', label: 'Any' },
        ],
        defaultValue: 'x64',
        isRequired: false,
        displayOrder: 6,
      },
    ],
  },
  {
    name: 'RPCS3 Fields',
    fields: [
      {
        name: 'renderer',
        label: 'Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan', label: 'Vulkan' },
          { value: 'OpenGL', label: 'OpenGL' },
        ],
        defaultValue: 'Vulkan',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 100,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 50,
        rangeMax: 300,
        rangeUnit: '%',
        rangeDecimals: 0,
      },
      {
        name: 'anisotropic_filter',
        label: 'Anisotropic Filter',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Automatic', label: 'Automatic' },
          { value: '2x', label: '2x' },
          { value: '4x', label: '4x' },
          { value: '8x', label: '8x' },
          { value: '16x', label: '16x' },
        ],
        defaultValue: 'Automatic',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'anti_aliasing',
        label: 'Anti-Aliasing',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Disabled', label: 'Disabled' },
          { value: 'FXAA', label: 'FXAA' },
          { value: 'SMAA', label: 'SMAA' },
        ],
        defaultValue: 'Disabled',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'frame_limit',
        label: 'Frame Limit',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Off', label: 'Off' },
          { value: '30', label: '30 FPS' },
          { value: '60', label: '60 FPS' },
          { value: 'Auto', label: 'Auto' },
        ],
        defaultValue: 'Auto',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'spu_threads',
        label: 'SPU Threads',
        type: CustomFieldType.RANGE,
        defaultValue: 2,
        isRequired: false,
        displayOrder: 7,
        rangeMin: 1,
        rangeMax: 6,
        rangeUnit: '',
        rangeDecimals: 0,
      },
      {
        name: 'spu_block_size',
        label: 'SPU Block Size',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Safe', label: 'Safe' },
          { value: 'Mega', label: 'Mega' },
          { value: 'Giga', label: 'Giga' },
        ],
        defaultValue: 'Safe',
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'Yuzu Fields',
    fields: [
      {
        name: 'api',
        label: 'API',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan', label: 'Vulkan' },
          { value: 'OpenGL', label: 'OpenGL' },
        ],
        defaultValue: 'Vulkan',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'anti_aliasing',
        label: 'Anti-Aliasing',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'None', label: 'None' },
          { value: 'FXAA', label: 'FXAA' },
          { value: 'SMAA', label: 'SMAA' },
        ],
        defaultValue: 'None',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'vsync_mode',
        label: 'VSync Mode',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Immediate (Off)', label: 'Immediate (Off)' },
          { value: 'Mailbox', label: 'Mailbox' },
          { value: 'FIFO (On)', label: 'FIFO (On)' },
          { value: 'FIFO Relaxed', label: 'FIFO Relaxed' },
        ],
        defaultValue: 'FIFO (On)',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'async_gpu_emulation',
        label: 'Async GPU Emulation',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'async_shader_compilation',
        label: 'Async Shader Compilation',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'cpu_accuracy',
        label: 'CPU Accuracy',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto', label: 'Auto' },
          { value: 'Accurate', label: 'Accurate' },
          { value: 'Unsafe', label: 'Unsafe' },
          { value: 'Paranoid', label: 'Paranoid' },
        ],
        defaultValue: 'Auto',
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'multicore_scheduling',
        label: 'Multicore CPU Emulation',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'Drastic Fields',
    fields: [
      {
        name: 'renderer',
        label: 'Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Software', label: 'Software' },
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'OpenGL ES', label: 'OpenGL ES' },
        ],
        defaultValue: 'OpenGL',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 4,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'texture_filtering',
        label: 'Texture Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'None', label: 'None' },
          { value: 'Linear', label: 'Linear' },
          { value: 'Nearest', label: 'Nearest' },
        ],
        defaultValue: 'Linear',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'frame_skip',
        label: 'Frame Skip',
        type: CustomFieldType.RANGE,
        defaultValue: 0,
        isRequired: false,
        displayOrder: 4,
        rangeMin: 0,
        rangeMax: 9,
        rangeUnit: '',
        rangeDecimals: 0,
      },
      {
        name: 'threaded_3d',
        label: 'Threaded 3D',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'high_resolution_3d',
        label: 'High Resolution 3D',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'jit_enabled',
        label: 'JIT Enabled',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'sound_enabled',
        label: 'Sound Enabled',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'melonDS Fields',
    fields: [
      {
        name: 'renderer',
        label: 'Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Software', label: 'Software' },
          { value: 'OpenGL', label: 'OpenGL' },
        ],
        defaultValue: 'OpenGL',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 8,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'texture_filtering',
        label: 'Texture Filtering',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'anti_aliasing',
        label: 'Anti-Aliasing',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'threaded_rendering',
        label: 'Threaded Rendering',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'jit_enabled',
        label: 'JIT Enabled',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'dsi_mode',
        label: 'DSi Mode',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'audio_interpolation',
        label: 'Audio Interpolation',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'None', label: 'None' },
          { value: 'Linear', label: 'Linear' },
          { value: 'Cosine', label: 'Cosine' },
          { value: 'Cubic', label: 'Cubic' },
        ],
        defaultValue: 'Linear',
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'Yaba Sanshiro Fields',
    fields: [
      {
        name: 'video_interface',
        label: 'Video Interface',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Software', label: 'Software' },
          { value: 'OpenGL ES 3.0', label: 'OpenGL ES 3.0' },
          { value: 'Vulkan', label: 'Vulkan' },
        ],
        defaultValue: 'OpenGL ES 3.0',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution',
        label: 'Resolution',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Original', label: 'Original' },
          { value: '2x', label: '2x' },
          { value: '4x', label: '4x' },
          { value: '720p', label: '720p' },
          { value: '1080p', label: '1080p' },
        ],
        defaultValue: 'Original',
        isRequired: false,
        displayOrder: 2,
      },
      {
        name: 'polygon_generation',
        label: 'Polygon Generation',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'CPU', label: 'CPU' },
          { value: 'GPU Tessellation', label: 'GPU Tessellation' },
          { value: 'GPU Compute Shader', label: 'GPU Compute Shader' },
        ],
        defaultValue: 'CPU',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'mesh_mode',
        label: 'Mesh Mode',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Original', label: 'Original' },
          { value: 'Improved', label: 'Improved' },
        ],
        defaultValue: 'Original',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'bandpass_filter',
        label: 'Bandpass Filter',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'rotate_screen',
        label: 'Rotate Screen',
        type: CustomFieldType.SELECT,
        options: [
          { value: '0', label: '0°' },
          { value: '90', label: '90°' },
          { value: '180', label: '180°' },
          { value: '270', label: '270°' },
        ],
        defaultValue: '0',
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'fps_mode',
        label: 'FPS Mode',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto', label: 'Auto' },
          { value: '50Hz', label: '50Hz' },
          { value: '60Hz', label: '60Hz' },
        ],
        defaultValue: 'Auto',
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'sound_engine',
        label: 'Sound Engine',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'New', label: 'New' },
          { value: 'Old', label: 'Old' },
        ],
        defaultValue: 'New',
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'Vita3K Fields',
    fields: [
      {
        name: 'backend_renderer',
        label: 'Backend Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'Vulkan', label: 'Vulkan' },
        ],
        defaultValue: 'OpenGL',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'gpu_backend',
        label: 'GPU Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Unicorn', label: 'Unicorn' },
          { value: 'Dynarmic', label: 'Dynarmic' },
        ],
        defaultValue: 'Dynarmic',
        isRequired: false,
        displayOrder: 2,
      },
      {
        name: 'resolution_multiplier',
        label: 'Resolution Multiplier',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 3,
        rangeMin: 1,
        rangeMax: 4,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'anisotropic_filtering',
        label: 'Anisotropic Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: '1x', label: '1x (Off)' },
          { value: '2x', label: '2x' },
          { value: '4x', label: '4x' },
          { value: '8x', label: '8x' },
          { value: '16x', label: '16x' },
        ],
        defaultValue: '1x',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'texture_cache',
        label: 'Texture Cache',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'shader_cache',
        label: 'Shader Cache',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'spirv_shader',
        label: 'SPIR-V Shader',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'ShadPS4 Fields',
    fields: [
      {
        name: 'gpu_backend',
        label: 'GPU Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan', label: 'Vulkan' },
          { value: 'OpenGL', label: 'OpenGL' },
        ],
        defaultValue: 'Vulkan',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_scale',
        label: 'Resolution Scale',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 4,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'anisotropic_filtering',
        label: 'Anisotropic Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Automatic', label: 'Automatic' },
          { value: '2x', label: '2x' },
          { value: '4x', label: '4x' },
          { value: '8x', label: '8x' },
          { value: '16x', label: '16x' },
        ],
        defaultValue: 'Automatic',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'enable_shader_validation',
        label: 'Enable Shader Validation',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'rdoc_enable',
        label: 'RenderDoc Enable',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'null_gpu',
        label: 'Null GPU',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'dump_shaders',
        label: 'Dump Shaders',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'Redream Fields',
    fields: [
      {
        name: 'backend',
        label: 'Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'Vulkan', label: 'Vulkan' },
        ],
        defaultValue: 'OpenGL',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution',
        label: 'Resolution',
        type: CustomFieldType.SELECT,
        options: [
          { value: '640x480', label: '640x480 (Original)' },
          { value: '1280x960', label: '1280x960 (2x)' },
          { value: '1920x1440', label: '1920x1440 (3x)' },
          { value: '2560x1920', label: '2560x1920 (4x)' },
        ],
        defaultValue: '640x480',
        isRequired: false,
        displayOrder: 2,
      },
      {
        name: 'region',
        label: 'Region',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto', label: 'Auto' },
          { value: 'Japan', label: 'Japan' },
          { value: 'USA', label: 'USA' },
          { value: 'Europe', label: 'Europe' },
        ],
        defaultValue: 'Auto',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'broadcast',
        label: 'Broadcast',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Auto', label: 'Auto' },
          { value: 'NTSC', label: 'NTSC' },
          { value: 'PAL', label: 'PAL' },
          { value: 'PAL_M', label: 'PAL-M' },
          { value: 'PAL_N', label: 'PAL-N' },
        ],
        defaultValue: 'Auto',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'language',
        label: 'Language',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Japanese', label: 'Japanese' },
          { value: 'English', label: 'English' },
          { value: 'German', label: 'German' },
          { value: 'French', label: 'French' },
          { value: 'Spanish', label: 'Spanish' },
          { value: 'Italian', label: 'Italian' },
        ],
        defaultValue: 'English',
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'audio_latency',
        label: 'Audio Latency',
        type: CustomFieldType.RANGE,
        defaultValue: 100,
        isRequired: false,
        displayOrder: 6,
        rangeMin: 20,
        rangeMax: 200,
        rangeUnit: 'ms',
        rangeDecimals: 0,
      },
      {
        name: 'enable_ta_stats',
        label: 'Enable TA Stats',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'enable_pvr_stats',
        label: 'Enable PVR Stats',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 8,
      },
    ],
  },
  {
    name: 'Citra Fields',
    fields: [
      {
        name: 'graphics_api',
        label: 'Graphics API',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'Software', label: 'Software' },
          { value: 'Vulkan', label: 'Vulkan' },
        ],
        defaultValue: 'OpenGL',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'resolution_factor',
        label: 'Resolution Factor',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 10,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'texture_filter',
        label: 'Texture Filter',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'None', label: 'None' },
          { value: 'Anime4K', label: 'Anime4K' },
          { value: 'Bicubic', label: 'Bicubic' },
          { value: 'ScaleForce', label: 'ScaleForce' },
          { value: 'xBRZ', label: 'xBRZ' },
        ],
        defaultValue: 'None',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'texture_sampling',
        label: 'Texture Sampling',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Game Controlled', label: 'Game Controlled' },
          { value: 'Nearest Neighbor', label: 'Nearest Neighbor' },
          { value: 'Linear', label: 'Linear' },
        ],
        defaultValue: 'Game Controlled',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'layout_option',
        label: 'Layout Option',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Default', label: 'Default' },
          { value: 'Single Screen', label: 'Single Screen' },
          { value: 'Large Screen', label: 'Large Screen' },
          { value: 'Side by Side', label: 'Side by Side' },
          { value: 'Separate Windows', label: 'Separate Windows' },
        ],
        defaultValue: 'Default',
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'swap_screen',
        label: 'Swap Screen',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'upright_screen',
        label: 'Upright Screen',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'use_hw_shader',
        label: 'Use Hardware Shader',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 8,
      },
      {
        name: 'use_shader_jit',
        label: 'Use Shader JIT',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 9,
      },
      {
        name: 'use_vsync_new',
        label: 'Use VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 10,
      },
      {
        name: 'shaders_accurate_mul',
        label: 'Shaders Accurate Multiplication',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 11,
      },
      {
        name: 'use_disk_shader_cache',
        label: 'Use Disk Shader Cache',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 12,
      },
    ],
  },
  {
    name: 'DuckStation Fields',
    fields: [
      {
        name: 'renderer',
        label: 'Renderer',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Vulkan (Recommended)', label: 'Vulkan (Recommended)' },
          { value: 'OpenGL', label: 'OpenGL' },
          { value: 'Direct3D 11 (PC)', label: 'Direct3D 11 (PC)' },
          { value: 'Direct3D 12 (PC)', label: 'Direct3D 12 (PC)' },
          { value: 'Software', label: 'Software' },
        ],
        defaultValue: 'Vulkan (Recommended)',
        isRequired: false,
        displayOrder: 1,
      },
      {
        name: 'internal_resolution',
        label: 'Internal Resolution',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 2,
        rangeMin: 1,
        rangeMax: 16,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'texture_filtering',
        label: 'Texture Filtering',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Nearest-Neighbor', label: 'Nearest-Neighbor' },
          { value: 'Bilinear', label: 'Bilinear' },
          {
            value: 'Bilinear (No Edge Blending)',
            label: 'Bilinear (No Edge Blending)',
          },
          { value: 'JINC2 (Slow)', label: 'JINC2 (Slow)' },
          { value: 'xBR (Very Slow)', label: 'xBR (Very Slow)' },
        ],
        defaultValue: 'Bilinear',
        isRequired: false,
        displayOrder: 3,
      },
      {
        name: 'anti_aliasing',
        label: 'Anti-Aliasing',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Disabled', label: 'Disabled' },
          { value: '2x MSAA', label: '2x MSAA' },
          { value: '4x MSAA', label: '4x MSAA' },
          { value: '8x MSAA', label: '8x MSAA' },
          { value: '16x MSAA', label: '16x MSAA' },
          { value: '2x SSAA', label: '2x SSAA' },
          { value: '4x SSAA', label: '4x SSAA' },
          { value: '8x SSAA', label: '8x SSAA' },
          { value: '16x SSAA', label: '16x SSAA' },
        ],
        defaultValue: 'Disabled',
        isRequired: false,
        displayOrder: 4,
      },
      {
        name: 'pgxp_geometry',
        label: 'PGXP Geometry Correction',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 5,
      },
      {
        name: 'pgxp_texture',
        label: 'PGXP Texture Correction',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 6,
      },
      {
        name: 'widescreen_hack',
        label: 'Widescreen Hack',
        type: CustomFieldType.BOOLEAN,
        defaultValue: false,
        isRequired: false,
        displayOrder: 7,
      },
      {
        name: 'cpu_overclock',
        label: 'CPU Overclock',
        type: CustomFieldType.RANGE,
        defaultValue: 100,
        isRequired: false,
        displayOrder: 8,
        rangeMin: 10,
        rangeMax: 1000,
        rangeUnit: '%',
        rangeDecimals: 0,
      },
      {
        name: 'gpu_overclock',
        label: 'GPU Overclock',
        type: CustomFieldType.RANGE,
        defaultValue: 100,
        isRequired: false,
        displayOrder: 9,
        rangeMin: 10,
        rangeMax: 2000,
        rangeUnit: '%',
        rangeDecimals: 0,
      },
      {
        name: 'cdrom_read_speedup',
        label: 'CD-ROM Read Speedup',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 10,
        rangeMin: 1,
        rangeMax: 10,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'cdrom_seek_speedup',
        label: 'CD-ROM Seek Speedup',
        type: CustomFieldType.RANGE,
        defaultValue: 1,
        isRequired: false,
        displayOrder: 11,
        rangeMin: 1,
        rangeMax: 20,
        rangeUnit: 'x',
        rangeDecimals: 0,
      },
      {
        name: 'vsync',
        label: 'VSync',
        type: CustomFieldType.BOOLEAN,
        defaultValue: true,
        isRequired: false,
        displayOrder: 12,
      },
      {
        name: 'audio_backend',
        label: 'Audio Backend',
        type: CustomFieldType.SELECT,
        options: [
          { value: 'Cubeb', label: 'Cubeb' },
          { value: 'SDL', label: 'SDL' },
          { value: 'XAudio2 (Windows)', label: 'XAudio2 (Windows)' },
          { value: 'Null', label: 'Null (No Audio)' },
        ],
        defaultValue: 'Cubeb',
        isRequired: false,
        displayOrder: 13,
      },
      {
        name: 'recompiler',
        label: 'CPU Recompiler',
        type: CustomFieldType.SELECT,
        options: [
          {
            value: 'Fastest (Cached Interpreter)',
            label: 'Fastest (Cached Interpreter)',
          },
          { value: 'Fast (Recompiler)', label: 'Fast (Recompiler)' },
          { value: 'Accurate (Interpreter)', label: 'Accurate (Interpreter)' },
        ],
        defaultValue: 'Fast (Recompiler)',
        isRequired: false,
        displayOrder: 14,
      },
      {
        name: 'memory_card_type',
        label: 'Memory Card Type',
        type: CustomFieldType.SELECT,
        options: [
          {
            value: 'Shared Between All Games',
            label: 'Shared Between All Games',
          },
          { value: 'Per Game', label: 'Per Game' },
          { value: 'Per Game Title', label: 'Per Game Title' },
          { value: 'None', label: 'None' },
        ],
        defaultValue: 'Per Game Title',
        isRequired: false,
        displayOrder: 15,
      },
    ],
  },
]

async function customFieldTemplatesSeeder(prisma: PrismaClient) {
  console.info('🌱 Seeding custom field templates...')

  for (const templateData of customFieldTemplates) {
    const { name, fields } = templateData

    // Create or update the template
    const template = await prisma.customFieldTemplate.upsert({
      where: { name },
      update: {},
      create: {
        name,
      },
    })

    // Remove existing fields and create new ones
    await prisma.customFieldTemplateField.deleteMany({
      where: { templateId: template.id },
    })

    for (const fieldData of fields) {
      await prisma.customFieldTemplateField.create({
        data: {
          templateId: template.id,
          name: fieldData.name,
          label: fieldData.label,
          type: fieldData.type,
          options: fieldData.options,
          defaultValue:
            fieldData.defaultValue !== undefined
              ? (fieldData.defaultValue as Prisma.InputJsonValue)
              : undefined,
          placeholder: fieldData.placeholder,
          isRequired: fieldData.isRequired,
          displayOrder: fieldData.displayOrder,
          rangeMin: fieldData.rangeMin,
          rangeMax: fieldData.rangeMax,
          rangeUnit: fieldData.rangeUnit,
          rangeDecimals: fieldData.rangeDecimals,
        },
      })
    }
  }

  console.info('✅ Custom field templates seeded successfully')
}

export default customFieldTemplatesSeeder
