import { type PrismaClient } from '@orm'

type SoCData = {
  name: string
  manufacturer: string
  architecture?: string
  processNode?: string
  cpuCores?: number
  gpuModel?: string
}

const socs: SoCData[] = [
  // Qualcomm Snapdragon
  {
    name: 'Snapdragon 8 Elite',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '3nm',
    cpuCores: 8,
    gpuModel: 'Adreno 830',
  },
  {
    name: 'Snapdragon 8 Gen 3',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 750',
  },
  {
    name: 'Snapdragon 7s Gen 2',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 710',
  },
  {
    name: 'Snapdragon 7+ Gen 2',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 725',
  },
  {
    name: 'Snapdragon 8+ Gen 1',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 730',
  },
  {
    name: 'Snapdragon 8 Gen 2',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 740',
  },
  {
    name: 'Snapdragon 7 Gen 1',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 662',
  },
  {
    name: 'Snapdragon 8 Gen 1',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Adreno 730',
  },
  {
    name: 'Snapdragon 778G',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Adreno 642L',
  },
  {
    name: 'Snapdragon 778G+',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Adreno 642L',
  },
  {
    name: 'Snapdragon 695',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Adreno 619',
  },
  {
    name: 'Snapdragon 768G',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 620',
  },
  {
    name: 'Snapdragon 765G',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 620',
  },
  {
    name: 'Snapdragon 870',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 650',
  },
  {
    name: 'Snapdragon 865',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 650',
  },
  {
    name: 'Snapdragon 855',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 640',
  },
  {
    name: 'Snapdragon 750G',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '8nm',
    cpuCores: 8,
    gpuModel: 'Adreno 619',
  },
  {
    name: 'Snapdragon 732G',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '8nm',
    cpuCores: 8,
    gpuModel: 'Adreno 618',
  },
  {
    name: 'Snapdragon 720G',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '8nm',
    cpuCores: 8,
    gpuModel: 'Adreno 618',
  },
  {
    name: 'Snapdragon 480+',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '8nm',
    cpuCores: 8,
    gpuModel: 'Adreno 619',
  },
  {
    name: 'Snapdragon 680',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Adreno 610',
  },
  {
    name: 'Snapdragon 662',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '11nm',
    cpuCores: 8,
    gpuModel: 'Adreno 610',
  },
  {
    name: 'Snapdragon 460',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '11nm',
    cpuCores: 8,
    gpuModel: 'Adreno 610',
  },
  {
    name: 'Snapdragon 439',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'Adreno 505',
  },
  {
    name: 'Snapdragon 888',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Adreno 660',
  },
  {
    name: 'Snapdragon 845',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '10nm',
    cpuCores: 8,
    gpuModel: 'Adreno 630',
  },
  {
    name: 'Snapdragon 865+',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 650',
  },
  {
    name: 'Snapdragon XR2',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Adreno 650',
  },
  {
    name: 'Snapdragon G3x Gen 1',
    manufacturer: 'Qualcomm',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Adreno 660',
  },

  // MediaTek Dimensity
  {
    name: 'Dimensity 9300',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Mali-G720',
  },
  {
    name: 'Dimensity 9200',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Mali-G715',
  },
  {
    name: 'Dimensity 9000',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Mali-G710',
  },
  {
    name: 'Dimensity 8300',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Mali-G615',
  },
  {
    name: 'Dimensity 1080',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G68',
  },
  {
    name: 'Dimensity 1200',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G77',
  },
  {
    name: 'MT6580A',
    manufacturer: 'MediaTek',
    architecture: 'ARM32',
    processNode: '28nm',
    cpuCores: 4,
    gpuModel: 'Mali-400 MP2',
  },
  {
    name: 'Helio G90T',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'Mali-G76 MC4',
  },
  {
    name: 'Helio P60',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'Mali-G72 MP3',
  },
  {
    name: 'Helio P22',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'PowerVR GE8320',
  },
  {
    name: 'Helio A22',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 4,
    gpuModel: 'PowerVR GE8320',
  },
  {
    name: 'Dimensity 8200',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Mali-G610 MC6',
  },
  {
    name: 'Dimensity 7200',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Mali-G610 MC4',
  },
  {
    name: 'Dimensity 6100+',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G57 MC2',
  },
  {
    name: 'Dimensity 7050',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G68 MC4',
  },
  {
    name: 'Dimensity 8020',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G77 MC9',
  },
  {
    name: 'Dimensity 920',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G68 MC4',
  },
  {
    name: 'Dimensity 810',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G57 MC2',
  },
  {
    name: 'Dimensity 700',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Mali-G57 MC2',
  },
  {
    name: 'Helio G35',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'PowerVR GE8320',
  },
  {
    name: 'Helio G25',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'PowerVR GE8320',
  },
  {
    name: 'Helio G37',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'PowerVR GE8320',
  },
  {
    name: 'Dimensity 1100',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G77 MC9',
  },
  {
    name: 'Dimensity 900',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G68 MC4',
  },
  {
    name: 'Helio G95',
    manufacturer: 'MediaTek',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'Mali-G76 MC4',
  },

  // Exynos
  {
    name: 'Exynos 2400',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 10,
    gpuModel: 'Xclipse 940',
  },
  {
    name: 'Exynos 2200',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Xclipse 920',
  },
  {
    name: 'Exynos 2100',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Mali-G78',
  },
  {
    name: 'Exynos 1480',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Xclipse 530',
  },
  {
    name: 'Exynos 1380',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Mali-G68',
  },
  {
    name: 'Exynos 1280',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Mali-G68',
  },
  {
    name: 'Exynos 990',
    manufacturer: 'Samsung',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Mali-G77',
  },

  // AMD
  {
    name: 'AMD Z1 Extreme',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'RDNA 3',
  },
  {
    name: 'AMD Z1',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '4nm',
    cpuCores: 6,
    gpuModel: 'RDNA 3',
  },
  {
    name: 'AMD Ryzen 7 6800U',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Radeon 680M',
  },
  {
    name: 'AMD Ryzen 7 7840U',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '4nm',
    cpuCores: 8,
    gpuModel: 'Radeon 780M',
  },
  {
    name: 'AMD Ryzen 7 5825U',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Radeon Vega 8',
  },
  {
    name: 'AMD Ryzen 7 5800U',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Radeon Vega 8',
  },
  {
    name: 'AMD Ryzen 5 5560U',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '7nm',
    cpuCores: 6,
    gpuModel: 'Radeon Vega 7',
  },
  {
    name: 'AMD Custom APU',
    manufacturer: 'AMD',
    architecture: 'x86_64',
    processNode: '7nm',
    cpuCores: 4,
    gpuModel: 'RDNA 2',
  },

  // Apple
  {
    name: 'Apple M4',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '3nm',
    cpuCores: 10,
    gpuModel: 'Apple GPU (10-core)',
  },
  {
    name: 'Apple M3',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '3nm',
    cpuCores: 8,
    gpuModel: 'Apple GPU (10-core)',
  },
  {
    name: 'Apple M2',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Apple GPU (10-core)',
  },
  {
    name: 'Apple M1',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 8,
    gpuModel: 'Apple GPU (8-core)',
  },
  {
    name: 'Apple A17 Pro',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '3nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (6-core)',
  },
  {
    name: 'Apple A16 Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '4nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (5-core)',
  },
  {
    name: 'Apple A15 Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (5-core)',
  },
  {
    name: 'Apple A14 Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '5nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (4-core)',
  },
  {
    name: 'Apple A13 Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (4-core)',
  },
  {
    name: 'Apple A12Z Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Apple GPU (8-core)',
  },
  {
    name: 'Apple A12X Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 8,
    gpuModel: 'Apple GPU (7-core)',
  },
  {
    name: 'Apple A12 Bionic',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '7nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (4-core)',
  },
  {
    name: 'Apple A10X Fusion',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '10nm',
    cpuCores: 6,
    gpuModel: 'Apple GPU (12-core)',
  },
  {
    name: 'Apple A10 Fusion',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '16nm',
    cpuCores: 4,
    gpuModel: 'PowerVR Series7XT GT7600 Plus',
  },
  {
    name: 'Apple A9X',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '16nm',
    cpuCores: 2,
    gpuModel: 'PowerVR Series7XT (12-core)',
  },
  {
    name: 'Apple A9',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '14nm/16nm',
    cpuCores: 2,
    gpuModel: 'PowerVR GT7600',
  },
  {
    name: 'Apple A8X',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '20nm',
    cpuCores: 3,
    gpuModel: 'PowerVR GX6650',
  },
  {
    name: 'Apple A8',
    manufacturer: 'Apple',
    architecture: 'ARM64',
    processNode: '20nm',
    cpuCores: 2,
    gpuModel: 'PowerVR GX6450',
  },

  // NVIDIA
  {
    name: 'Tegra X1',
    manufacturer: 'NVIDIA',
    architecture: 'ARM64',
    processNode: '20nm',
    cpuCores: 4,
    gpuModel: 'Maxwell',
  },

  // Unisoc
  {
    name: 'Tiger T820',
    manufacturer: 'Unisoc',
    architecture: 'ARM64',
    processNode: '6nm',
    cpuCores: 8,
    gpuModel: 'Mali-G57',
  },
  {
    name: 'Tiger T618',
    manufacturer: 'Unisoc',
    architecture: 'ARM64',
    processNode: '12nm',
    cpuCores: 8,
    gpuModel: 'Mali-G52',
  },

  // Allwinner
  {
    name: 'Allwinner H700',
    manufacturer: 'Allwinner',
    architecture: 'ARM64',
    processNode: '22nm',
    cpuCores: 4,
    gpuModel: 'Mali-G31',
  },
  {
    name: 'Allwinner A133',
    manufacturer: 'Allwinner',
    architecture: 'ARM64',
    processNode: '22nm',
    cpuCores: 4,
    gpuModel: 'PowerVR GE8300',
  },

  // Rockchip
  {
    name: 'RK3566',
    manufacturer: 'Rockchip',
    architecture: 'ARM64',
    processNode: '22nm',
    cpuCores: 4,
    gpuModel: 'Mali-G52',
  },
  {
    name: 'RK3588',
    manufacturer: 'Rockchip',
    architecture: 'ARM64',
    processNode: '8nm',
    cpuCores: 8,
    gpuModel: 'Mali-G610',
  },

  // Intel
  {
    name: 'Intel Core Ultra 7 155H',
    manufacturer: 'Intel',
    architecture: 'x86_64',
    processNode: '7nm',
    cpuCores: 16,
    gpuModel: 'Intel Arc',
  },
]

async function socSeeder(prisma: PrismaClient) {
  console.log('�� Seeding SoCs...')

  for (const soc of socs) {
    await prisma.soC.upsert({
      where: { name: soc.name },
      update: {},
      create: soc,
    })
  }

  console.log('✅ SoCs seeded successfully')
}

export default socSeeder
